/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unnecessary-type-assertion */
/* eslint-disable @typescript-eslint/no-non-null-assertion */
/* eslint-disable @typescript-eslint/strict-boolean-expressions */
/* eslint-disable curly */
import { BaseSeeder } from "@adonisjs/lucid/seeders";
import db from "@adonisjs/lucid/services/db";

import Condition from "#models/condition";
import Route from "#models/route";
import RouteStop from "#models/route_stop";
import Schedule from "#models/schedule";
import Stop from "#models/stop";

export default class extends BaseSeeder {
  public async run() {
    // 1. Tworzenie warunków (Conditions)
    await Condition.updateOrCreateMany("name", [
      {
        name: "D",
        description: "Kursuje od poniedziałku do piątku oprócz świąt",
      },
      {
        name: "ą",
        description: "Nie kursuje 2.V i w piątek po Bożym Ciele",
      },
      { name: "m", description: "Nie kursuje w dniach 24 i 31.XII" },
      {
        name: "6x",
        description: "Kursuje w soboty powszednie oprócz Wielkiej Soboty",
      },
      { name: "(1)-(7)", description: "Kursuje codziennie" },
      { name: "(C)", description: "Kursuje w soboty, niedziele i święta" },
    ]);
    const conditions = await Condition.all();
    const conditionMap = new Map(
      conditions.map((condition) => [condition.name, condition.id]),
    );

    // 2. Pełna lista unikalnych przystanków z przypisanym typem
    const stopsData = [
      // Przystanki autobusowe
      { name: "KRAPKOWICE OS. 1000L", coords: [17.973, 50.479], type: "bus" },
      {
        name: "Krapkowice ul. 1 Maja (Rondo)",
        coords: [17.971, 50.476],
        type: "bus",
      },
      {
        name: "Krapkowice ul. Drzymały (Targ)",
        coords: [17.969, 50.475],
        type: "bus",
      },
      {
        name: "Krapkowice ul. Opolska II",
        coords: [17.966, 50.476],
        type: "bus",
      },
      {
        name: "Krapkowice ul. Opolska I",
        coords: [17.962, 50.478],
        type: "bus",
      },
      {
        name: "Krapkowice ul. Opolska III",
        coords: [17.957, 50.48],
        type: "bus",
      },
      { name: "Otmęt SZPS", coords: [17.954, 50.484], type: "bus" },
      { name: "Otmęt ul. Kilińskiego", coords: [17.956, 50.486], type: "bus" },
      { name: "Osiedle Sady I", coords: [17.96, 50.49], type: "bus" },
      { name: "Osiedle Sady II", coords: [17.963, 50.492], type: "bus" },
      { name: "Otmęt Skrzyżowanie", coords: [17.968, 50.491], type: "bus" },
      { name: "Otmęt Martinex", coords: [17.973, 50.49], type: "bus" },
      { name: "Otmęt UMIG", coords: [17.976, 50.489], type: "bus" },
      {
        name: "Gogolin ul. Krapkowicka I",
        coords: [18.013, 50.489],
        type: "bus",
      },
      {
        name: "Gogolin ul. Krapkowicka II",
        coords: [18.018, 50.489],
        type: "bus",
      },
      { name: "GOGOLIN CENTRUM", coords: [18.026, 50.49], type: "bus" },
      {
        name: "KRAPKOWICE | ul. Prudnicka",
        coords: [17.965, 50.471],
        type: "bus",
      },
      {
        name: "KRAPKOWICE | Osiedle 1000-lecia",
        coords: [17.973, 50.478],
        type: "bus",
      },
      {
        name: "KRAPKOWICE | ul. Głowackiego",
        coords: [17.969, 50.483],
        type: "bus",
      },
      {
        name: "KRAPKOWICE | ul. Ks. Koziołka",
        coords: [17.981, 50.488],
        type: "bus",
      },
      { name: "KRAPKOWICE | Kaufland", coords: [17.986, 50.489], type: "bus" },
      {
        name: "GOGOLIN | Hala Sportowa",
        coords: [18.006, 50.489],
        type: "bus",
      },
      {
        name: "GOGOLIN | ul. Krapkowicka",
        coords: [18.018, 50.489],
        type: "bus",
      },
      {
        name: "GOGOLIN | Dworzec Kolejowy",
        coords: [18.024, 50.491],
        type: "bus",
      },
      {
        name: "GOGOLIN | ul. Strzelecka",
        coords: [18.031, 50.49],
        type: "bus",
      },
      { name: "GOGOLIN | Zakrzów", coords: [18.046, 50.489], type: "bus" },
      { name: "ZAKRZÓW | SHR", coords: [18.058, 50.485], type: "bus" },
      { name: "DĄBRÓWKA", coords: [18.082, 50.468], type: "bus" },
      { name: "LIGOTA DOLNA", coords: [18.105, 50.457], type: "bus" },
      { name: "NIWKI", coords: [18.125, 50.449], type: "bus" },
      { name: "KALINOWICE | St. P-ta", coords: [18.14, 50.439], type: "bus" },
      {
        name: "KALINOWICE | Skrzyżowanie",
        coords: [18.151, 50.435],
        type: "bus",
      },
      { name: "KALINÓW", coords: [18.175, 50.428], type: "bus" },
      { name: "ROŻNIĄTÓW", coords: [18.212, 50.42], type: "bus" },
      {
        name: "STRZELCE OPOLSKIE | AGR",
        coords: [18.258, 50.411],
        type: "bus",
      },
      {
        name: "STRZELCE OPOLSKIE | ul. Powstańców Śl.",
        coords: [18.275, 50.41],
        type: "bus",
      },
      {
        name: "STRZELCE OPOLSKIE | Dworzec PKP",
        coords: [18.291, 50.409],
        type: "bus",
      },
      {
        name: "STRZELCE OPOLSKIE | ul. Krakowska",
        coords: [18.303, 50.412],
        type: "bus",
      },
      { name: "KRAPKOWICE | Dworzec", coords: [17.968, 50.474], type: "bus" },
      // Stacje kolejowe
      { name: "KĘDZIERZYN-KOŹLE", coords: [18.204, 50.345], type: "train" },
      { name: "RASZOWA", coords: [18.121, 50.443], type: "train" },
      { name: "ZDZIESZOWICE", coords: [18.115, 50.424], type: "train" },
      { name: "JASIONA", coords: [18.067, 50.456], type: "train" },
      { name: "GOGOLIN", coords: [18.025, 50.49], type: "train" },
      { name: "GÓRAŻDŻE", coords: [17.984, 50.508], type: "train" },
      { name: "PRZYWORY OPOLSKIE", coords: [17.94, 50.551], type: "train" },
      { name: "OPOLE GROTOWICE", coords: [17.93, 50.59], type: "train" },
      { name: "OPOLE GROSZOWICE", coords: [17.938, 50.633], type: "train" },
      { name: "OPOLE GŁÓWNE", coords: [17.925, 50.662], type: "train" },
    ];

    // 3. Pełne dane rozkładów jazdy
    const scheduleData = [
      // DANE DLA AUTOBUSÓW
      {
        routeName: "PKS Krapkowice - Gogolin",
        operator: "PKS w Strzelcach Op. S.A.",
        type: "bus", // Typ trasy
        directions: [
          {
            destination: "GOGOLIN CENTRUM PRZESIADKOWE",
            stopSchedules: [
              {
                stopName: "KRAPKOWICE OS. 1000L",
                weekdayTimes: [
                  "05:15",
                  "06:30",
                  "07:30",
                  "09:00",
                  "12:15",
                  "13:40",
                  "14:55",
                  "15:55",
                  "17:25",
                  "18:40",
                  "20:00",
                  "20:55",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["06:15", "08:20", "11:25", "15:30"],
              },
              {
                stopName: "Krapkowice ul. 1 Maja (Rondo)",
                weekdayTimes: [
                  "05:17",
                  "06:32",
                  "07:32",
                  "09:02",
                  "12:17",
                  "13:42",
                  "14:56",
                  "15:57",
                  "17:27",
                  "18:42",
                  "20:02",
                  "20:57",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["06:17", "08:22", "11:27", "15:32"],
              },
              {
                stopName: "Krapkowice ul. Drzymały (Targ)",
                weekdayTimes: [
                  "05:18",
                  "06:33",
                  "07:33",
                  "09:03",
                  "12:18",
                  "13:43",
                  "15:00",
                  "15:58",
                  "17:28",
                  "18:43",
                  "20:03",
                  "20:58",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["06:18", "08:23", "11:28", "15:33"],
              },
              {
                stopName: "Krapkowice ul. Opolska II",
                weekdayTimes: [
                  "05:19",
                  "06:34",
                  "07:34",
                  "09:04",
                  "12:19",
                  "13:44",
                  "15:01",
                  "15:59",
                  "17:29",
                  "18:44",
                  "20:04",
                  "20:59",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["06:19", "08:24", "11:29", "15:34"],
              },
              {
                stopName: "Krapkowice ul. Opolska I",
                weekdayTimes: [
                  "05:21",
                  "06:36",
                  "07:36",
                  "09:06",
                  "12:21",
                  "13:46",
                  "15:03",
                  "16:01",
                  "17:31",
                  "18:46",
                  "20:06",
                  "21:01",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["06:21", "08:26", "11:31", "15:36"],
              },
              {
                stopName: "Krapkowice ul. Opolska III",
                weekdayTimes: [
                  "05:23",
                  "06:39",
                  "07:38",
                  "09:09",
                  "12:23",
                  "13:49",
                  "15:05",
                  "16:04",
                  "17:33",
                  "18:49",
                  "20:08",
                  "21:04",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["06:24", "08:28", "11:34", "15:38"],
              },
              {
                stopName: "Otmęt SZPS",
                weekdayTimes: [
                  "05:26",
                  "06:42",
                  "07:41",
                  "09:12",
                  "12:26",
                  "13:52",
                  "15:08",
                  "16:07",
                  "17:36",
                  "18:52",
                  "20:11",
                  "21:07",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["06:27", "08:31", "11:37", "15:41"],
              },
              {
                stopName: "Otmęt ul. Kilińskiego",
                weekdayTimes: [
                  "05:27",
                  null,
                  "07:42",
                  null,
                  "12:27",
                  null,
                  "15:10",
                  null,
                  "17:37",
                  null,
                  "20:12",
                  null,
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [null, "08:32", null, "15:42"],
              },
              {
                stopName: "Osiedle Sady I",
                weekdayTimes: [
                  null,
                  "06:44",
                  null,
                  "09:14",
                  null,
                  "13:54",
                  null,
                  "16:09",
                  null,
                  "18:54",
                  null,
                  "21:09",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["06:29", null, "11:39", null],
              },
              {
                stopName: "Osiedle Sady II",
                weekdayTimes: [
                  null,
                  "06:45",
                  null,
                  "09:15",
                  null,
                  "13:55",
                  null,
                  "16:10",
                  null,
                  "18:55",
                  null,
                  "21:10",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["06:30", null, "11:40", null],
              },
              {
                stopName: "Otmęt Skrzyżowanie",
                weekdayTimes: [
                  null,
                  "06:47",
                  null,
                  "09:17",
                  null,
                  "13:57",
                  null,
                  "16:12",
                  null,
                  null,
                  null,
                  "21:12",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["06:32", null, "11:42", null],
              },
              {
                stopName: "Otmęt Martinex",
                weekdayTimes: [
                  "05:28",
                  "06:48",
                  "07:43",
                  "09:18",
                  "12:28",
                  "13:58",
                  "15:11",
                  "16:13",
                  "17:38",
                  "18:58",
                  "20:13",
                  "21:13",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["06:33", "08:33", "11:43", "15:43"],
              },
              {
                stopName: "Otmęt UMIG",
                weekdayTimes: [
                  "05:29",
                  "06:49",
                  "07:44",
                  "09:19",
                  "12:29",
                  "13:59",
                  "15:12",
                  "16:14",
                  "17:39",
                  "18:59",
                  "20:14",
                  "21:14",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["06:34", "08:34", "11:44", "15:44"],
              },
              {
                stopName: "KRAPKOWICE | ul. Ks. Koziołka",
                weekdayTimes: [
                  "05:30",
                  "06:50",
                  "07:45",
                  "09:20",
                  "12:30",
                  "14:00",
                  "15:15",
                  "16:15",
                  "17:40",
                  "19:00",
                  "20:15",
                  "21:15",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["06:35", "08:35", "11:45", "15:45"],
              },
              {
                stopName: "Gogolin ul. Krapkowicka I",
                weekdayTimes: [
                  "05:32",
                  "06:52",
                  "07:47",
                  "09:22",
                  "12:32",
                  "14:02",
                  "15:17",
                  "16:17",
                  "17:42",
                  "19:02",
                  "20:17",
                  "21:17",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["06:37", "08:37", "11:47", "15:47"],
              },
              {
                stopName: "Gogolin ul. Krapkowicka II",
                weekdayTimes: [
                  "05:33",
                  "06:53",
                  "07:48",
                  "09:23",
                  "12:33",
                  "14:03",
                  "15:18",
                  "16:18",
                  "17:43",
                  "19:03",
                  "20:18",
                  "21:18",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["06:38", "08:38", "11:48", "15:48"],
              },
              {
                stopName: "GOGOLIN CENTRUM",
                weekdayTimes: [
                  "05:35",
                  "06:55",
                  "07:50",
                  "09:25",
                  "12:35",
                  "14:05",
                  "15:20",
                  "16:20",
                  "17:45",
                  "19:05",
                  "20:20",
                  "21:20",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["06:40", "08:40", "11:50", "15:50"],
              },
            ],
          },
          {
            destination: "KRAPKOWICE OS. 1000L",
            stopSchedules: [
              {
                stopName: "GOGOLIN CENTRUM",
                weekdayTimes: [
                  "06:00",
                  "07:05",
                  "08:15",
                  "09:30",
                  "13:00",
                  "14:10",
                  "15:25",
                  "16:20",
                  "18:05",
                  "19:20",
                  "20:25",
                  "21:55",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["07:15", "09:10", "12:10", "16:20"],
              },
              {
                stopName: "Gogolin ul. Krapkowicka II",
                weekdayTimes: [
                  "06:02",
                  "07:07",
                  "08:17",
                  "09:32",
                  "13:02",
                  "14:12",
                  "15:27",
                  "16:22",
                  "18:07",
                  "19:22",
                  "20:27",
                  "21:57",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["07:17", "09:12", "12:12", "16:22"],
              },
              {
                stopName: "Gogolin ul. Krapkowicka I",
                weekdayTimes: [
                  "06:03",
                  "07:08",
                  "08:19",
                  "09:33",
                  "13:04",
                  "14:13",
                  "15:29",
                  "16:23",
                  "18:09",
                  "19:23",
                  "20:29",
                  "21:58",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["07:19", "09:13", "12:14", "16:23"],
              },
              {
                stopName: "KRAPKOWICE | ul. Ks. Koziołka",
                weekdayTimes: [
                  "06:05",
                  "07:10",
                  "08:21",
                  "09:35",
                  "13:06",
                  "14:15",
                  "15:31",
                  "16:25",
                  "18:11",
                  "19:25",
                  "20:31",
                  "22:00",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["07:21", "09:15", "12:16", "16:25"],
              },
              {
                stopName: "Otmęt UMIG",
                weekdayTimes: [
                  "06:06",
                  "07:11",
                  "08:22",
                  "09:36",
                  "13:07",
                  "14:16",
                  "15:32",
                  "16:26",
                  "18:12",
                  "19:26",
                  "20:32",
                  "22:01",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["07:22", "09:16", "12:17", "16:26"],
              },
              {
                stopName: "Otmęt Skrzyżowanie",
                weekdayTimes: [
                  null,
                  null,
                  "08:24",
                  null,
                  "13:09",
                  null,
                  "15:34",
                  null,
                  "18:14",
                  null,
                  "20:34",
                  null,
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["07:24", null, "12:19", null],
              },
              {
                stopName: "Osiedle Sady II",
                weekdayTimes: [
                  null,
                  null,
                  "08:26",
                  null,
                  "13:11",
                  null,
                  "15:36",
                  null,
                  "18:16",
                  null,
                  "20:36",
                  null,
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["07:26", null, "12:21", null],
              },
              {
                stopName: "Otmęt ul. Kilińskiego",
                weekdayTimes: [
                  "06:08",
                  "07:13",
                  null,
                  "09:38",
                  null,
                  "14:18",
                  null,
                  "16:28",
                  null,
                  "19:28",
                  null,
                  "22:03",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [null, "09:18", null, "16:28"],
              },
              {
                stopName: "Otmęt SZPS",
                weekdayTimes: [
                  "06:09",
                  "07:14",
                  "08:28",
                  "09:39",
                  "13:13",
                  "14:19",
                  "15:38",
                  "16:29",
                  "18:18",
                  "19:29",
                  "20:38",
                  "22:04",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["07:28", "09:19", "12:23", "16:29"],
              },
              {
                stopName: "Krapkowice ul. Opolska I",
                weekdayTimes: [
                  "06:14",
                  "07:19",
                  "08:33",
                  "09:44",
                  "13:18",
                  "14:24",
                  "15:43",
                  "16:34",
                  "18:23",
                  "19:34",
                  "20:43",
                  "22:09",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["07:33", "09:24", "12:28", "16:34"],
              },
              {
                stopName: "Krapkowice ul. Opolska II",
                weekdayTimes: [
                  "06:16",
                  "07:21",
                  "08:35",
                  "09:46",
                  "13:20",
                  "14:26",
                  "15:45",
                  "16:36",
                  "18:25",
                  "19:36",
                  "20:45",
                  "22:11",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["07:35", "09:26", "12:30", "16:36"],
              },
              {
                stopName: "Krapkowice ul. Opolska III",
                weekdayTimes: [
                  "06:17",
                  "07:22",
                  "08:37",
                  "09:47",
                  "13:22",
                  "14:27",
                  "15:47",
                  "16:37",
                  "18:27",
                  "19:37",
                  "20:47",
                  "22:12",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["07:37", "09:27", "12:32", "16:37"],
              },
              {
                stopName: "KRAPKOWICE OS. 1000L",
                weekdayTimes: [
                  "06:20",
                  "07:25",
                  "08:40",
                  "09:50",
                  "13:25",
                  "14:30",
                  "15:50",
                  "16:40",
                  "18:30",
                  "19:40",
                  "20:50",
                  "22:15",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: ["07:40", "09:30", "12:35", "16:40"],
              },
            ],
          },
        ],
      },
      {
        routeName: "LUZ Krapkowice - Strzelce Opolskie",
        operator: "LUZ",
        type: "bus", // Typ trasy
        directions: [
          {
            destination: "STRZELCE OPOLSKIE",
            stopSchedules: [
              {
                stopName: "KRAPKOWICE | ul. Prudnicka",
                weekdayTimes: [
                  "06:50",
                  "07:30",
                  "09:00",
                  "09:45",
                  "10:50",
                  "14:15",
                  "15:10",
                  "16:15",
                  "17:15",
                  "18:20",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "KRAPKOWICE | Osiedle 1000-lecia",
                weekdayTimes: [
                  "06:51",
                  "07:31",
                  "09:01",
                  "09:46",
                  "10:51",
                  "14:16",
                  "15:11",
                  "16:16",
                  "17:16",
                  "18:21",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "KRAPKOWICE | ul. Głowackiego",
                weekdayTimes: [
                  "06:52",
                  "07:32",
                  "09:02",
                  "09:47",
                  "10:52",
                  "14:17",
                  "15:12",
                  "16:17",
                  "17:17",
                  "18:22",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "KRAPKOWICE | ul. Ks. Koziołka",
                weekdayTimes: [
                  "06:54",
                  "07:34",
                  "09:04",
                  "09:49",
                  "10:54",
                  "14:19",
                  "15:14",
                  "16:19",
                  "17:19",
                  "18:24",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "KRAPKOWICE | Kaufland",
                weekdayTimes: [
                  "06:55",
                  "07:35",
                  "09:05",
                  "09:50",
                  "10:55",
                  "14:20",
                  "15:15",
                  "16:20",
                  "17:20",
                  "18:25",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "GOGOLIN | Hala Sportowa",
                weekdayTimes: [
                  "06:57",
                  "07:37",
                  "09:07",
                  "09:52",
                  "10:57",
                  "14:22",
                  "15:17",
                  "16:22",
                  "17:22",
                  "18:27",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "GOGOLIN | ul. Krapkowicka",
                weekdayTimes: [
                  "06:59",
                  "07:39",
                  "09:09",
                  "09:54",
                  "10:59",
                  "14:24",
                  "15:19",
                  "16:24",
                  "17:24",
                  "18:29",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "GOGOLIN | Dworzec Kolejowy",
                weekdayTimes: [
                  "07:01",
                  "07:41",
                  "09:11",
                  "09:56",
                  "11:01",
                  "14:26",
                  "15:21",
                  "16:26",
                  "17:26",
                  "18:31",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "GOGOLIN | ul. Strzelecka",
                weekdayTimes: [
                  "07:03",
                  "07:43",
                  "09:13",
                  "09:58",
                  "11:03",
                  "14:28",
                  "15:23",
                  "16:28",
                  "17:28",
                  "18:33",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "GOGOLIN | Zakrzów",
                weekdayTimes: [
                  "07:05",
                  "07:45",
                  "09:15",
                  "10:00",
                  "11:05",
                  "14:30",
                  "15:25",
                  "16:30",
                  "17:30",
                  "18:35",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "ZAKRZÓW | SHR",
                weekdayTimes: [
                  "07:07",
                  "07:47",
                  "09:17",
                  "10:02",
                  "11:07",
                  "14:32",
                  "15:27",
                  "16:32",
                  "17:32",
                  "18:37",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "DĄBRÓWKA",
                weekdayTimes: [
                  "07:08",
                  "07:48",
                  "09:18",
                  "10:03",
                  "11:08",
                  "14:33",
                  "15:28",
                  "16:33",
                  "17:33",
                  "18:38",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "LIGOTA DOLNA",
                weekdayTimes: [
                  "07:10",
                  "07:50",
                  "09:20",
                  "10:05",
                  "11:10",
                  "14:35",
                  "15:30",
                  "16:35",
                  "17:35",
                  "18:40",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "NIWKI",
                weekdayTimes: [
                  "07:13",
                  "07:53",
                  "09:23",
                  "10:08",
                  "11:13",
                  "14:38",
                  "15:33",
                  "16:38",
                  "17:38",
                  "18:43",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "KALINOWICE | St. P-ta",
                weekdayTimes: [
                  "07:14",
                  "07:54",
                  "09:24",
                  "10:09",
                  "11:14",
                  "14:39",
                  "15:34",
                  "16:39",
                  "17:39",
                  "18:44",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "KALINOWICE | Skrzyżowanie",
                weekdayTimes: [
                  "07:16",
                  "07:56",
                  "09:26",
                  "10:11",
                  "11:16",
                  "14:41",
                  "15:36",
                  "16:41",
                  "17:41",
                  "18:46",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "KALINÓW",
                weekdayTimes: [
                  "07:18",
                  "07:58",
                  "09:28",
                  "10:13",
                  "11:18",
                  "14:43",
                  "15:38",
                  "16:43",
                  "17:43",
                  "18:48",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "ROŻNIĄTÓW",
                weekdayTimes: [
                  "07:21",
                  "08:01",
                  "09:31",
                  "10:16",
                  "11:21",
                  "14:46",
                  "15:41",
                  "16:46",
                  "17:46",
                  "18:51",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "STRZELCE OPOLSKIE | AGR",
                weekdayTimes: [
                  "07:24",
                  "08:04",
                  "09:34",
                  "10:19",
                  "11:24",
                  "14:49",
                  "15:44",
                  "16:49",
                  "17:49",
                  "18:54",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "STRZELCE OPOLSKIE | ul. Powstańców Śl.",
                weekdayTimes: [
                  "07:26",
                  "08:06",
                  "09:36",
                  "10:21",
                  "11:26",
                  "14:51",
                  "15:46",
                  "16:51",
                  "17:51",
                  "18:56",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "STRZELCE OPOLSKIE | Dworzec PKP",
                weekdayTimes: [
                  "07:28",
                  "08:08",
                  "09:38",
                  "10:23",
                  "11:28",
                  "14:53",
                  "15:48",
                  "16:53",
                  "17:53",
                  "18:58",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "STRZELCE OPOLSKIE | ul. Krakowska",
                weekdayTimes: [
                  "07:30",
                  "08:10",
                  "09:40",
                  "10:25",
                  "11:30",
                  "14:55",
                  "15:50",
                  "16:55",
                  "17:55",
                  "19:00",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
            ],
          },
          {
            destination: "KRAPKOWICE",
            stopSchedules: [
              {
                stopName: "STRZELCE OPOLSKIE | ul. Krakowska",
                weekdayTimes: [
                  "05:50",
                  "06:45",
                  "08:05",
                  "08:55",
                  "10:05",
                  "13:15",
                  "14:10",
                  "15:10",
                  "16:15",
                  "17:35",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "STRZELCE OPOLSKIE | Dworzec PKP",
                weekdayTimes: [
                  "05:52",
                  "06:47",
                  "08:07",
                  "08:57",
                  "10:07",
                  "13:17",
                  "14:12",
                  "15:12",
                  "16:17",
                  "17:37",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "STRZELCE OPOLSKIE | AGR",
                weekdayTimes: [
                  "05:56",
                  "06:51",
                  "08:11",
                  "09:01",
                  "10:11",
                  "13:21",
                  "14:16",
                  "15:16",
                  "16:21",
                  "17:41",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "ROŻNIĄTÓW",
                weekdayTimes: [
                  "05:59",
                  "06:54",
                  "08:14",
                  "09:04",
                  "10:14",
                  "13:24",
                  "14:19",
                  "15:19",
                  "16:24",
                  "17:44",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "KALINÓW",
                weekdayTimes: [
                  "06:02",
                  "06:57",
                  "08:17",
                  "09:07",
                  "10:17",
                  "13:27",
                  "14:22",
                  "15:22",
                  "16:27",
                  "17:47",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "KALINOWICE | Skrzyżowanie",
                weekdayTimes: [
                  "06:04",
                  "06:59",
                  "08:19",
                  "09:09",
                  "10:19",
                  "13:29",
                  "14:24",
                  "15:24",
                  "16:29",
                  "17:49",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "KALINOWICE | St. P-ta",
                weekdayTimes: [
                  "06:06",
                  "07:01",
                  "08:21",
                  "09:11",
                  "10:21",
                  "13:31",
                  "14:26",
                  "15:26",
                  "16:31",
                  "17:51",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "NIWKI",
                weekdayTimes: [
                  "06:07",
                  "07:02",
                  "08:22",
                  "09:12",
                  "10:22",
                  "13:32",
                  "14:27",
                  "15:27",
                  "16:32",
                  "17:52",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "LIGOTA DOLNA",
                weekdayTimes: [
                  "06:10",
                  "07:05",
                  "08:25",
                  "09:15",
                  "10:25",
                  "13:35",
                  "14:30",
                  "15:30",
                  "16:35",
                  "17:55",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "DĄBRÓWKA",
                weekdayTimes: [
                  "06:12",
                  "07:07",
                  "08:27",
                  "09:17",
                  "10:27",
                  "13:37",
                  "14:32",
                  "15:32",
                  "16:37",
                  "17:57",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "ZAKRZÓW | SHR",
                weekdayTimes: [
                  "06:13",
                  "07:08",
                  "08:28",
                  "09:18",
                  "10:28",
                  "13:38",
                  "14:33",
                  "15:33",
                  "16:38",
                  "17:58",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "GOGOLIN | Zakrzów",
                weekdayTimes: [
                  "06:15",
                  "07:10",
                  "08:30",
                  "09:20",
                  "10:30",
                  "13:40",
                  "14:35",
                  "15:35",
                  "16:40",
                  "18:00",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "GOGOLIN | ul. Strzelecka",
                weekdayTimes: [
                  "06:17",
                  "07:12",
                  "08:32",
                  "09:22",
                  "10:32",
                  "13:42",
                  "14:37",
                  "15:37",
                  "16:42",
                  "18:02",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "GOGOLIN | Dworzec Kolejowy",
                weekdayTimes: [
                  "06:19",
                  "07:14",
                  "08:34",
                  "09:24",
                  "10:34",
                  "13:44",
                  "14:39",
                  "15:39",
                  "16:44",
                  "18:04",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "GOGOLIN | ul. Krapkowicka",
                weekdayTimes: [
                  "06:21",
                  "07:16",
                  "08:36",
                  "09:26",
                  "10:36",
                  "13:46",
                  "14:41",
                  "15:41",
                  "16:46",
                  "18:06",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "GOGOLIN | Hala Sportowa",
                weekdayTimes: [
                  "06:23",
                  "07:18",
                  "08:38",
                  "09:28",
                  "10:38",
                  "13:48",
                  "14:43",
                  "15:43",
                  "16:48",
                  "18:08",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "KRAPKOWICE | Kaufland",
                weekdayTimes: [
                  "06:25",
                  "07:20",
                  "08:40",
                  "09:30",
                  "10:40",
                  "13:50",
                  "14:45",
                  "15:45",
                  "16:50",
                  "18:10",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "KRAPKOWICE | ul. Ks. Koziołka",
                weekdayTimes: [
                  "06:26",
                  "07:21",
                  "08:41",
                  "09:31",
                  "10:41",
                  "13:51",
                  "14:46",
                  "15:46",
                  "16:51",
                  "18:11",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "KRAPKOWICE | Dworzec",
                weekdayTimes: [
                  "06:28",
                  "07:23",
                  "08:43",
                  "09:33",
                  "10:43",
                  "13:53",
                  "14:48",
                  "15:48",
                  "16:53",
                  "18:13",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "KRAPKOWICE | Osiedle 1000-lecia",
                weekdayTimes: [
                  "06:29",
                  "07:24",
                  "08:44",
                  "09:34",
                  "10:44",
                  "13:54",
                  "14:49",
                  "15:49",
                  "16:54",
                  "18:14",
                ],

                weekendHolidayTimes: [],
                dailyTimes: [],
                saturdayTimes: [],
              },
              {
                stopName: "KRAPKOWICE | ul. Prudnicka",
                weekdayTimes: [
                  "06:30",
                  "07:25",
                  "08:45",
                  "09:35",
                  "10:45",
                  "13:55",
                  "14:50",
                  "15:50",
                  "16:55",
                  "18:15",
                ],

                saturdayTimes: [],
                weekendHolidayTimes: [],
                dailyTimes: [],
              },
            ],
          },
        ],
      },
      // DANE DLA POCIĄGÓW
      {
        routeName: "POLREGIO Kędzierzyn-Koźle - Opole Główne",
        operator: "POLREGIO",
        type: "train", // Typ trasy
        directions: [
          {
            destination: "OPOLE GŁÓWNE",
            stopSchedules: [
              {
                saturdayTimes: [],
                stopName: "KĘDZIERZYN-KOŹLE",
                weekdayTimes: [
                  "04:11",
                  "04:44",
                  "05:33",
                  "06:16",
                  "06:54",
                  "08:36",
                  "09:16",
                  "11:45",
                  "12:25",
                  "14:16",
                  "14:55",
                  "15:17",
                  "15:58",
                  "16:33",
                  "17:43",
                  "18:22",
                  "18:39",
                  "20:15",
                  "21:25",
                  "22:29",
                ],
                dailyTimes: ["05:08", "07:43", "09:25", "20:09"],
                weekendHolidayTimes: ["16:33", "22:28"],
              },
              {
                saturdayTimes: [],
                stopName: "RASZOWA",
                weekdayTimes: [
                  "04:17",
                  "04:49",
                  "05:38",
                  "06:21",
                  "06:59",
                  "08:42",
                  "09:21",
                  "11:50",
                  "12:30",
                  "14:21",
                  "15:00",
                  "15:23",
                  "16:03",
                  "16:39",
                  "17:49",
                  "18:29",
                  "18:44",
                  "20:20",
                  "21:31",
                  "22:35",
                ],
                dailyTimes: ["05:14", "07:48", "11:54", "20:20"],
                weekendHolidayTimes: ["16:39", "22:35"],
              },
              {
                saturdayTimes: [],
                stopName: "ZDZIESZOWICE",
                weekdayTimes: [
                  "04:21",
                  "04:53",
                  "05:42",
                  "06:25",
                  "07:03",
                  "08:47",
                  "09:25",
                  "11:54",
                  "12:34",
                  "14:26",
                  "15:05",
                  "15:27",
                  "16:08",
                  "16:43",
                  "17:52",
                  "18:35",
                  "18:48",
                  "20:34",
                  "21:35",
                  "22:39",
                ],
                dailyTimes: ["05:18", "07:52", "12:34", "20:34"],
                weekendHolidayTimes: ["16:43", "22:39"],
              },
              {
                saturdayTimes: [],
                stopName: "JASIONA",
                weekdayTimes: [
                  "04:25",
                  "04:57",
                  "05:46",
                  "06:29",
                  "07:07",
                  "08:51",
                  "09:29",
                  "11:58",
                  "12:38",
                  "14:30",
                  "15:09",
                  "15:31",
                  "16:12",
                  "16:47",
                  "17:57",
                  null,
                  "18:52",
                  "20:38",
                  "21:39",
                  "22:43",
                ],
                dailyTimes: ["05:22", "07:56", "12:38", "20:38"],
                weekendHolidayTimes: ["16:47", "22:43"],
              },
              {
                saturdayTimes: [],
                stopName: "GOGOLIN",
                weekdayTimes: [
                  "04:30",
                  "05:02",
                  "05:51",
                  "06:34",
                  "07:12",
                  "08:56",
                  "09:34",
                  "12:03",
                  "12:43",
                  "14:34",
                  "15:14",
                  "15:35",
                  "16:16",
                  "16:51",
                  "18:01",
                  "18:35",
                  "18:56",
                  "20:42",
                  "21:43",
                  "22:47",
                ],
                dailyTimes: ["05:26", "08:01", "12:43", "20:42"],
                weekendHolidayTimes: ["16:51", "22:47"],
              },
              {
                saturdayTimes: [],
                stopName: "GÓRAŻDŻE",
                weekdayTimes: [
                  "04:34",
                  "05:05",
                  "05:54",
                  "06:37",
                  "07:16",
                  "09:00",
                  "09:37",
                  "12:06",
                  "12:47",
                  "14:38",
                  "15:17",
                  "15:39",
                  "16:20",
                  "16:55",
                  "18:05",
                  null,
                  "19:00",
                  "20:46",
                  "21:47",
                  "22:51",
                ],
                dailyTimes: ["05:30", "08:04", "12:47", "20:46"],
                weekendHolidayTimes: ["16:55", "22:51"],
              },
              {
                saturdayTimes: [],
                stopName: "PRZYWORY OPOLSKIE",
                weekdayTimes: [
                  "04:38",
                  "05:10",
                  "05:58",
                  "06:42",
                  "07:20",
                  "09:05",
                  "09:41",
                  "12:11",
                  "12:51",
                  "14:42",
                  "15:21",
                  "15:43",
                  "16:25",
                  "16:59",
                  "18:09",
                  null,
                  "19:04",
                  "20:50",
                  "21:51",
                  "22:56",
                ],
                dailyTimes: ["05:35", "08:08", "12:51", "20:50"],
                weekendHolidayTimes: ["16:59", "22:56"],
              },
              {
                saturdayTimes: [],
                stopName: "OPOLE GROTOWICE",
                weekdayTimes: [
                  "04:42",
                  "05:13",
                  "06:01",
                  "06:45",
                  "07:23",
                  "09:09",
                  "09:44",
                  "12:14",
                  "12:54",
                  "14:45",
                  "15:25",
                  "15:46",
                  "16:28",
                  "17:02",
                  "18:13",
                  null,
                  "19:08",
                  "20:54",
                  "21:54",
                  "22:59",
                ],
                dailyTimes: ["05:38", "08:11", "12:54", "20:54"],
                weekendHolidayTimes: ["17:02", "22:59"],
              },
              {
                saturdayTimes: [],
                stopName: "OPOLE GROSZOWICE",
                weekdayTimes: [
                  "04:45",
                  "05:16",
                  "06:05",
                  "06:48",
                  "07:27",
                  "09:12",
                  "09:47",
                  "12:17",
                  "12:58",
                  "14:48",
                  "15:28",
                  "15:49",
                  "16:32",
                  "17:05",
                  "18:16",
                  null,
                  "19:11",
                  "20:57",
                  "21:57",
                  "23:02",
                ],
                dailyTimes: ["05:41", "08:15", "12:58", "20:57"],
                weekendHolidayTimes: ["17:05", "23:02"],
              },
              {
                saturdayTimes: [],
                stopName: "OPOLE GŁÓWNE",
                weekdayTimes: [
                  "04:50",
                  "05:20",
                  "06:09",
                  "06:52",
                  "07:30",
                  "09:18",
                  "09:50",
                  "12:21",
                  "13:01",
                  "14:52",
                  "15:31",
                  "15:52",
                  "16:35",
                  "17:10",
                  "18:20",
                  "18:47",
                  "19:14",
                  "21:01",
                  "22:02",
                  "23:07",
                ],
                dailyTimes: ["05:44", "08:18", "13:01", "21:01"],
                weekendHolidayTimes: ["17:10", "23:07"],
              },
            ],
          },
          {
            destination: "KĘDZIERZYN-KOŹLE",
            stopSchedules: [
              {
                saturdayTimes: [],
                stopName: "OPOLE GŁÓWNE",
                weekdayTimes: [
                  "05:30",
                  "06:24",
                  "08:47",
                  "09:36",
                  "10:56",
                  "12:32",
                  "13:36",
                  "14:27",
                  "15:45",
                  "16:46",
                  "17:20",
                  "19:08",
                  "19:46",
                  "21:10",
                  "22:29",
                  "23:06",
                  "23:38",
                ],
                dailyTimes: ["06:44", "07:45", "18:11", "22:54", "23:35"],
                weekendHolidayTimes: ["06:59", "17:30"],
              },
              {
                saturdayTimes: [],
                stopName: "OPOLE GROSZOWICE",
                weekdayTimes: [
                  "05:33",
                  "06:27",
                  "08:51",
                  "09:39",
                  "10:59",
                  "12:35",
                  "13:40",
                  "14:30",
                  "15:48",
                  "16:49",
                  "17:23",
                  "19:11",
                  "19:49",
                  "21:13",
                  "22:33",
                  "23:09",
                  "23:41",
                ],
                dailyTimes: ["06:48", "07:49", "18:14", "23:09", "23:41"],
                weekendHolidayTimes: ["07:03", "17:34"],
              },
              {
                saturdayTimes: [],
                stopName: "OPOLE GROTOWICE",
                weekdayTimes: [
                  "05:36",
                  "06:30",
                  "08:54",
                  "09:43",
                  "11:02",
                  "12:38",
                  "13:43",
                  "14:33",
                  "15:51",
                  "16:52",
                  "17:26",
                  "19:14",
                  "19:52",
                  "21:16",
                  "22:36",
                  "23:12",
                  "23:44",
                ],
                dailyTimes: ["06:51", "07:53", "18:17", "23:12", "23:44"],
                weekendHolidayTimes: ["07:06", "17:37"],
              },
              {
                saturdayTimes: [],
                stopName: "PRZYWORY OPOLSKIE",
                weekdayTimes: [
                  "05:40",
                  "06:33",
                  "08:57",
                  "09:46",
                  "11:06",
                  "12:41",
                  "13:46",
                  "14:36",
                  "15:55",
                  "16:56",
                  "17:29",
                  "19:17",
                  "19:56",
                  "21:20",
                  "22:40",
                  "23:15",
                  "23:47",
                ],
                dailyTimes: ["06:54", "07:56", "18:20", "23:15", "23:47"],
                weekendHolidayTimes: ["07:09", "17:40"],
              },
              {
                saturdayTimes: [],
                stopName: "GÓRAŻDŻE",
                weekdayTimes: [
                  "05:44",
                  "06:38",
                  "09:02",
                  "09:51",
                  "11:10",
                  "12:46",
                  "13:50",
                  "14:40",
                  "15:59",
                  "17:00",
                  "17:33",
                  "19:21",
                  "20:00",
                  "21:24",
                  "22:45",
                  "23:19",
                  "23:52",
                ],
                dailyTimes: ["06:58", "08:01", "18:25", "23:19", "23:52"],
                weekendHolidayTimes: ["07:13", "17:44"],
              },
              {
                saturdayTimes: [],
                stopName: "GOGOLIN",
                weekdayTimes: [
                  "05:48",
                  "06:42",
                  "09:05",
                  "09:54",
                  "11:14",
                  "12:50",
                  "13:54",
                  "14:44",
                  "16:03",
                  "17:04",
                  "17:37",
                  "19:25",
                  "20:04",
                  "21:28",
                  "22:49",
                  "23:23",
                  "23:56",
                ],
                dailyTimes: ["07:02", "08:05", "18:29", "23:23", "23:56"],
                weekendHolidayTimes: ["07:17", "17:49"],
              },
              {
                saturdayTimes: [],
                stopName: "JASIONA",
                weekdayTimes: [
                  "05:53",
                  "06:46",
                  "09:10",
                  "09:59",
                  "11:18",
                  "12:54",
                  "13:58",
                  "14:48",
                  "16:07",
                  "17:09",
                  "17:41",
                  "19:29",
                  "20:08",
                  "21:32",
                  "22:54",
                  "23:27",
                  "00:00",
                ],
                dailyTimes: ["07:06", "08:10", "18:33", "23:27", "00:00"],
                weekendHolidayTimes: ["07:21", "17:53"],
              },
              {
                saturdayTimes: [],
                stopName: "ZDZIESZOWICE",
                weekdayTimes: [
                  "05:57",
                  "06:51",
                  "09:15",
                  "10:03",
                  "11:23",
                  "12:59",
                  "14:03",
                  "14:52",
                  "16:12",
                  "17:13",
                  "17:45",
                  "19:33",
                  "20:13",
                  "21:37",
                  "22:59",
                  "23:31",
                  "00:05",
                ],
                dailyTimes: ["07:10", "08:15", "18:38", "23:31", "00:05"],
                weekendHolidayTimes: ["07:25", "17:58"],
              },
              {
                saturdayTimes: [],
                stopName: "RASZOWA",
                weekdayTimes: [
                  "06:02",
                  "06:55",
                  "09:18",
                  "10:07",
                  "11:27",
                  "13:03",
                  "14:07",
                  "14:56",
                  "16:16",
                  "17:17",
                  "17:49",
                  "19:37",
                  "20:17",
                  "21:41",
                  "23:03",
                  "23:34",
                  "00:09",
                ],
                dailyTimes: ["07:14", "08:19", "18:42", "23:34", "00:09"],
                weekendHolidayTimes: ["07:29", "18:02"],
              },
              {
                saturdayTimes: [],
                stopName: "KĘDZIERZYN-KOŹLE",
                weekdayTimes: [
                  "06:07",
                  "07:00",
                  "09:23",
                  "10:13",
                  "11:33",
                  "13:08",
                  "14:11",
                  "15:00",
                  "16:21",
                  "17:22",
                  "17:54",
                  "19:42",
                  "20:21",
                  "21:47",
                  "23:09",
                  "23:40",
                  "00:14",
                ],
                dailyTimes: ["07:19", "08:25", "18:47", "23:40", "00:14"],
                weekendHolidayTimes: ["07:34", "18:07"],
              },
            ],
          },
        ],
      },
    ];

    // --- LOGIKA SEEDERA ---

    const stopMap = new Map<string, Stop>();
    for (const stopData of stopsData) {
      const geoJSONString = JSON.stringify({
        type: "Point",
        coordinates: stopData.coords,
      });
      const stop = await Stop.updateOrCreate(
        { name: stopData.name },
        {
          location: db.raw("ST_GeomFromGeoJSON(?)", [geoJSONString]) as any,
          type: stopData.type as any,
        },
      );
      stopMap.set(stopData.name, stop);
    }

    let globalRunCounter = 1;

    for (const routeData of scheduleData) {
      const route = await Route.updateOrCreate(
        { name: routeData.routeName },
        { operator: routeData.operator, type: routeData.type as any },
      );

      // Zbierz wszystkie unikalne przystanki dla całej trasy (obu kierunków)
      const uniqueStopNames = new Set<string>();
      for (const direction of routeData.directions) {
        for (const stopSchedule of direction.stopSchedules) {
          uniqueStopNames.add(stopSchedule.stopName);
        }
      }

      // Stwórz powiązania Route-Stop
      const routeStopMap = new Map<string, RouteStop>();
      for (const stopName of uniqueStopNames) {
        const stop = stopMap.get(stopName);
        if (!stop) {
          continue;
        }
        const routeStop = await RouteStop.firstOrCreate({
          routeId: route.id,
          stopId: stop.id,
        });
        routeStopMap.set(`${route.id}-${stop.id}`, routeStop);
      }

      // Przetwarzaj kierunki i przebiegi
      for (const direction of routeData.directions) {
        const processRuns = async (
          timesKey:
            | "weekdayTimes"
            | "saturdayTimes"
            | "dailyTimes"
            | "weekendHolidayTimes",
          typeNames: string[],
        ) => {
          if (
            !direction.stopSchedules[0] ||
            !(timesKey in direction.stopSchedules[0])
          )
            return;

          const numRuns = (direction.stopSchedules[0] as any)[timesKey]!.length;
          if (numRuns === 0) return;

          const conditionIds = typeNames
            .map((name) => conditionMap.get(name)!)
            .filter((id) => id);

          for (let runIndex = 0; runIndex < numRuns; runIndex++) {
            // Użyj pętli z indeksem, aby uzyskać `sequence`
            for (const [
              stopIndex,
              stopSchedule,
            ] of direction.stopSchedules.entries()) {
              const time = (stopSchedule as any)[timesKey]?.[runIndex];
              if (!time) continue;

              const stop = stopMap.get(stopSchedule.stopName)!;
              const routeStop = routeStopMap.get(`${route.id}-${stop.id}`)!;

              // ZMIANA: Dodaj `sequence` do tworzenia/aktualizacji rekordu Schedule
              const schedule = await Schedule.updateOrCreate(
                {
                  routeStopId: routeStop.id,
                  run: globalRunCounter,
                },
                {
                  time: `${time}:00`,
                  destination: direction.destination,
                  sequence: stopIndex + 1, // Użyj indeksu przystanku w kierunku jako sekwencji
                },
              );
              await schedule.related("conditions").sync(conditionIds);
            }
            globalRunCounter++;
          }
        };

        if (routeData.operator === "PKS w Strzelcach Op. S.A.") {
          await processRuns("weekdayTimes", ["D", "ą", "m"]);
          await processRuns("saturdayTimes", ["6x"]);
        } else if (routeData.operator === "LUZ") {
          await processRuns("weekdayTimes", ["D"]);
        } else if (routeData.operator === "POLREGIO") {
          await processRuns("weekdayTimes", ["D"]);
          await processRuns("dailyTimes", ["(1)-(7)"]);
          await processRuns("weekendHolidayTimes", ["(C)"]);
        }
      }
    }
  }
}
